name: .NET Build and Test

on:
  push:
#    branches: [ "main" ]
  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use a specific version or keep 'x' for latest patch

    - name: Restore dependencies
      run: dotnet restore DDDProject.sln

    - name: Build
      run: dotnet build DDDProject.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test DDDProject.sln --no-build --verbosity normal --configuration Release 